version: 0.0
os: linux
#files:
#  - source: docker/middleman_docker_image.tar.gz
#    destination: /tmp
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 1
      runas: ec2-user
  AfterInstall:
    - location: scripts/load_image.sh
      timeout: 1.5
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 1
      runas: ec2-user
