version: 0.0
os: linux
#files:
#  - source: docker/middleman_docker_image.tar.gz
#    destination: /tmp
hooks:
  ApplicationStop:
    - location: kill_container.sh
      timeout: 2
      runas: ec2-user
  AfterInstall:
    - location: load_image.sh
      timeout: 2.5
      runas: ec2-user
  ApplicationStart:
    - location: start_container.sh
      timeout: 2
      runas: ec2-user
