version: 0.0
os: linux
files:
  - source: ./
    destination: /tmp/code-deploy_tasker
hooks:
  ApplicationStop:
    - location: kill_container.sh
      timeout: 2
      runas: root
  AfterInstall:
    - location: load_image.sh
      timeout: 2.5
      runas: root
  ApplicationStart:
    - location: start_container.sh
      timeout: 2
      runas: ec2-user
